// ========== CONSTANTES Y CONFIGURACIÓN ==========
const BULLET_RADIUS = 1;
const BULLET_MAX_DISTANCE = 333;
const REGION_WIDTH = 600;
const REGION_HEIGHT = 600;
const SECTOR_WIDTH = REGION_WIDTH / 3;
const SECTOR_HEIGHT = REGION_HEIGHT / 3;
const MAX_LIVES = 99;
const LOAD_RADIUS = 2;
const REGION_UNLOAD_DISTANCE = 4;
const MIN_OBSTACLE_DISTANCE = 30;