// ========== ESTADO DEL JUEGO ==========
let gameState = {
    playerX: 900,
    playerY: 900,
    playerRotation: 0,
    playerSpeed: 3.75,
    turboMode: false,
    turboActive: false,
    turboCurrent: 12.0,
    turboMax: 12.0,
    turboDepletionRate: 0.5,
    turboRechargeRate: 0.25,
    turboAngle: 0,
    score: 0,
    hits: 0,
    wallsDestroyed: 0,
    specialHits: 0,
    greenHits: 0,
    pestilenceDamageReceived: 0,
    splashDamageReceived: 0,
    tentacleDamageReceived: 0,
    tentaclesDestroyed: 0,
    rifleShots: 0,
    shotgunShots: 0,
    machinegunShots: 0,
    minigunShots: 0,
    mouseX: 300,
    mouseY: 300,
    gameStarted: false,
    gameActive: true,
    playerLives: 99,
    playerSlowZonesCount: 0,
    cameraX: 0,
    cameraY: 0,
    currentRegionX: 1,
    currentRegionY: 1,
    isSpecialEvent: false,
    mergingEnemies: false,
    currentEnemyCount: 0,
    orangeEnemiesToCreate: 30,
    fuchsiaEnemiesCount: 0,
    greenEnemiesCount: 0,
    keys: {},
    projectiles: [],
    enemies: [],
    obstacles: [],
    playerPrevX: 900,
    playerPrevY: 900,
    stains: [],
    minimapVisible: false,
    centralRegionTemplate: {
        obstacles: [],
        enemies: []
    },
    shotsFired: 0,
    canShoot: true,
    isCooldownActive: false,
    cooldownTimer: null,
    lastTurboUpdate: 0,
    turboRequested: false,
    turboRunning: false,
    
    currentLevel: 0,
    previousLevel: 0,
    maxLevelReached: 0,
    regionBackgrounds: [],
    levelUpdateCooldown: 0,
    exploredRegions: new Set(),
    
    isOnRubble: false,
    rubbleDeviationX: 0,
    rubbleDeviationY: 0,
    rubbleEffectActive: false,
    lastRubbleCheck: 0,
    
    isInCorpse: false,
    lastCorpseDamage: 0,
    cooldownWeaponType: null
};